services:
     - type: web
       name: excelapp
       runtime: php
       rootDir: SERVIDOR
       buildCommand: |
         composer install --no-dev --optimize-autoloader
         php artisan config:cache
         php artisan route:cache
         php artisan view:cache
         php artisan storage:link
         php artisan migrate --force
       startCommand: php artisan serve --host=0.0.0.0 --port=10000
       envVars:
         - key: APP_ENV
           value: production
         - key: APP_DEBUG
           value: false
